###
GET http://localhost:8080/api/welcome

### 
GET http://localhost:8080/api/products
Content-Type: application/json


###
POST http://localhost:8080/api/products
Content-Type: application/json

{
    "name": "HP",
    "description": "Samsung",
    "price": 1500000
}

### 
GET http://localhost:8080/api/products/1
Content-Type: application/json

###
PUT http://localhost:8080/api/products
Content-Type: application/json

{
    "id": 1,
    "name": "HP updated",
    "description": "Samsung",
    "price": 1500000
}

### 
DELETE http://localhost:8080/api/products/1
Content-Type: application/json